<WinScreen>:
    
            
    Image:
        id:backgr
        size_hint:1,1
        source:'image/wi/rose.png'
    
    MDLabel:
        text:"Feel free to contact me at youness.amhaouch@gmail.com for your ideas and advices ... I'm happy that you finished this game."
        size_hint:.8,.5
        font_size:.15*self.height
        pos_hint:{'center_x':.5,'center_y':.5}
        halign:'center'
    

